name: variant-calling
channels:
  - defaults
  - bioconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - bcftools=1.21=h8b25389_0
  - blas=2.137=openblas
  - blas-devel=3.9.0=37_h1ea3ea9_openblas
  - boost-cpp=1.74.0=h6cacc03_7
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h4eded50_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - coreutils=9.5=hd590300_0
  - curl=8.8.0=he654da7_1
  - dbus=1.13.6=h5008d03_3
  - expat=2.7.1=hecca717_0
  - falco=1.2.4=hdcf5f25_0
  - fastp=0.23.4=h125f33a_4
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.16=hb03c661_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=hac33072_2
  - graalpy=23.0.0=0_graalvm_native
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=4.2.0=h40b6f09_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.21=h5efdd21_0
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.14.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=69.1=h9c3ff4c_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - isa-l=2.30.0=h7f8727e_0
  - java-jdk=8.0.92=1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - k8=0.2.5=hdcf5f25_4
  - kaleido-core=0.2.1=h3644ca4_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb9589c4_0
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libcblas=3.9.0=37_h0358290_openblas
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.80.2=hf974151_0
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblapacke=3.9.0=37_h6ae95b6_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.5.1=hffd6297_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - mathjax=2.7.7=ha770c72_3
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minimap2=2.28=he4a0461_3
  - multiqc=1.32=pyhdfd78af_1
  - narwhals=2.10.0=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - nextflow=0.24.2=0
  - nspr=4.37=h29cc59b_0
  - nss=3.100=hca3bf56_0
  - numpy=2.2.5=py310hc213724_2
  - numpy-base=2.2.5=py310hf387b04_2
  - octopus=0.7.4=ha3c1580_2
  - openblas=0.3.30=pthreads_h6ec200e_2
  - openjdk=21.0.6=h38aa4c6_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.50.7=hbd2fdc8_0
  - patch=2.8=hb03c661_1002
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - pillow=11.1.0=py310hcea889d_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plotly=6.3.1=pyhd8ed1ab_0
  - polars=1.34.0=pyh6a1acc5_0
  - polars-lts-cpu=1.34.0.deprecated=hc364b38_0
  - polars-runtime-32=1.34.0=py310hbdd6827_0
  - polars-runtime-compat=1.34.0=py310hbdd6827_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.8=0_native230_graalpy
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python_abi=3.10=8_graalpy230_310_native
  - pyyaml=6.0.3=pyh7db6752_0
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.9.1=py310hee96239_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-click=1.9.4=pyhd8ed1ab_0
  - rpds-py=0.22.3=py310h4aa5aa6_0
  - sambamba=1.0.1=h6f6fda4_2
  - samtools=1.21=h50ea8bc_0
  - setuptools=80.9.0=pyhff2d567_0
  - spectra=0.0.11=pyhd8ed1ab_2
  - sqlite=3.46.0=h6d4b2fc_0
  - tiktoken=0.9.0=py310h52b74c6_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py310h2c38b39_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - annotated-doc==0.0.4
      - anyio==4.12.0
      - exceptiongroup==1.3.1
      - fastapi==0.99.1
      - h11==0.16.0
      - pydantic==1.10.24
      - python-multipart==0.0.6
      - starlette==0.27.0
      - uvicorn==0.38.0
prefix: /home/sarthak/anaconda3/envs/variant-calling
